// customers.ts — 20 életszerű ügyfél a seedhez. A mezőnevek camelCase-ben, pontosan a
// schema.prisma Customer modelljéhez igazítva (mint a plants.ts) — nincs mapping lépés.
//
// A HÁROM ELSŐ KÓD SZÁNDÉKOSAN A RÉGI: az ACME / GLOBEX / INITECH a 03. alkalom óta
// szerepel a doksik példáiban ("Mit ajánlasz az ACME-nek?"), és a büdzséjük is a régi.
// Az ACME 1 000 Ft-os kerete nem elírás: a docs/ora-04-zaro-ellenorzes.md rögzíti, hogy
// arra egyetlen raktáron lévő növény jött — ha átírjuk, az a mérés hazuggá válik.
// A régi careLevel átváltása: ALACSONY → kezdő, KÖZEPES → haladó, MAGAS → profi.

export const customers = [
  {
    code: 'ACME',
    name: 'Acme Irodaház Kft.',
    contactName: 'Tóth Márton',
    email: 'marton.toth@acme.hu',
    city: 'Budapest',
    customerType: 'iroda',
    budget: 1000,
    expertiseLevel: 'kezdő',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Északi tájolású tárgyaló, gyenge fény. Senki nem akar öntözni, a takarítók locsolnak hetente egyszer.',
  },
  {
    code: 'GLOBEX',
    name: 'Globex Zrt.',
    contactName: 'Kiss Réka',
    email: 'reka.kiss@globex.hu',
    city: 'Budapest',
    customerType: 'iroda',
    budget: 5000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Nagy üvegfelület, déli fény. Modern, letisztult stílus, kevés de nagy növény.',
  },
  {
    code: 'INITECH',
    name: 'Initech Solutions Kft.',
    contactName: 'Balogh Dániel',
    email: 'daniel.balogh@initech.hu',
    city: 'Debrecen',
    customerType: 'iroda',
    budget: 250000,
    expertiseLevel: 'profi',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Saját kertész jár be kéthetente. Ritka, mutatós fajokat keresnek a recepcióra.',
  },
  {
    code: 'BOROSTYAN',
    name: 'Borostyán Étterem',
    contactName: 'Fekete Zsolt',
    email: 'zsolt@borostyanetterem.hu',
    city: 'Szentendre',
    customerType: 'étterem',
    budget: 180000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: true,
    notes:
      'Családi étterem, gyerekbarát terasz. Párás konyhatér, oda igénytelen faj kell.',
  },
  {
    code: 'NAPFENY',
    name: 'Napfény Hotel',
    contactName: 'Molnár Ágnes',
    email: 'agnes.molnar@napfenyhotel.hu',
    city: 'Siófok',
    customerType: 'hotel',
    budget: 450000,
    expertiseLevel: 'profi',
    petSafeRequired: true,
    kidSafeRequired: true,
    notes:
      'Kutyabarát hotel, gyerekes vendégekkel. Lobbi erős fény, folyosók árnyékosak.',
  },
  {
    code: 'KOVACS',
    name: 'Kovács Anna',
    contactName: null,
    email: 'anna.kovacs@gmail.com',
    city: 'Pécs',
    customerType: 'magánszemély',
    budget: 35000,
    expertiseLevel: 'kezdő',
    petSafeRequired: true,
    kidSafeRequired: false,
    notes:
      'Két macska. Panellakás, keleti ablak. Most kezd növényezni, ne haljon meg egyből.',
  },
  {
    code: 'ZOLD',
    name: 'Zöld Sarok Kávézó',
    contactName: 'Simon Bence',
    email: 'bence@zoldsarok.hu',
    city: 'Szeged',
    customerType: 'étterem',
    budget: 90000,
    expertiseLevel: 'kezdő',
    petSafeRequired: true,
    kidSafeRequired: false,
    notes:
      'Kutyás vendégek. Sok lógó növényt szeretnének a pult fölé, kevés gondozással.',
  },
  {
    code: 'DUNAPART',
    name: 'Dunapart Irodaház',
    contactName: 'Németh Krisztina',
    email: 'krisztina.nemeth@dunapart.hu',
    city: 'Budapest',
    customerType: 'iroda',
    budget: 320000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Atrium, felülvilágító. Nagy, magasra növő fákat keresnek a belső térbe.',
  },
  {
    code: 'SZABO',
    name: 'Szabó Péter',
    contactName: null,
    email: 'peter.szabo@freemail.hu',
    city: 'Győr',
    customerType: 'magánszemély',
    budget: 60000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes: 'Déli erkély, nyáron tűző nap. Pozsgásokat és kaktuszokat gyűjt.',
  },
  {
    code: 'VITRIN',
    name: 'Vitrin Divatáru',
    contactName: 'Lakatos Dóra',
    email: 'dora@vitrin.hu',
    city: 'Budapest',
    customerType: 'üzlet',
    budget: 75000,
    expertiseLevel: 'kezdő',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Kirakat, erős szórt fény. Fontos a látvány, a gondozásra nincs kapacitás.',
  },
  {
    code: 'LOMBIK',
    name: 'Lombik Bisztró',
    contactName: 'Farkas Tamás',
    email: 'tamas@lombikbisztro.hu',
    city: 'Budapest',
    customerType: 'étterem',
    budget: 120000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes: 'Fűszernövényeket is szeretnének a konyhához, nemcsak dísznövényt.',
  },
  {
    code: 'TERASZ',
    name: 'Terasz Panzió',
    contactName: 'Juhász Ildikó',
    email: 'ildiko@teraszpanzio.hu',
    city: 'Eger',
    customerType: 'hotel',
    budget: 210000,
    expertiseLevel: 'kezdő',
    petSafeRequired: false,
    kidSafeRequired: true,
    notes:
      'Kültéri terasz és beltéri társalgó. Télen fagymentes tárolás megoldott.',
  },
  {
    code: 'NAGY',
    name: 'Nagy család',
    contactName: 'Nagy Zoltán',
    email: 'nagy.zoltan@gmail.com',
    city: 'Kecskemét',
    customerType: 'magánszemély',
    budget: 45000,
    expertiseLevel: 'kezdő',
    petSafeRequired: true,
    kidSafeRequired: true,
    notes:
      'Két kisgyerek és egy kutya. MINDEN növénynek biztonságosnak kell lennie.',
  },
  {
    code: 'ATRIUM',
    name: 'Átrium Coworking',
    contactName: 'Papp Levente',
    email: 'levente@atriumcowork.hu',
    city: 'Budapest',
    customerType: 'iroda',
    budget: 500000,
    expertiseLevel: 'profi',
    petSafeRequired: true,
    kidSafeRequired: false,
    notes:
      'Kutyabarát coworking. Levegőtisztító fajokat kérnek, ez marketing-érv náluk.',
  },
  {
    code: 'MOKKA',
    name: 'Mokka Pörkölő',
    contactName: 'Takács Bianka',
    email: 'bianka@mokkaporkolo.hu',
    city: 'Miskolc',
    customerType: 'üzlet',
    budget: 55000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Kis alapterület, polcokra való apró növények. Meleg, száraz levegő a pörkölő mellett.',
  },
  {
    code: 'VARGA',
    name: 'Varga Eszter',
    contactName: null,
    email: 'eszter.varga@gmail.com',
    city: 'Szombathely',
    customerType: 'magánszemély',
    budget: 25000,
    expertiseLevel: 'kezdő',
    petSafeRequired: false,
    kidSafeRequired: true,
    notes:
      'Első lakás, kis büdzsé. Egy nagyobb növényt szeretne a nappaliba, nem többet.',
  },
  {
    code: 'LIGET',
    name: 'Liget Wellness Hotel',
    contactName: 'Sipos Márk',
    email: 'mark.sipos@ligetwellness.hu',
    city: 'Hévíz',
    customerType: 'hotel',
    budget: 680000,
    expertiseLevel: 'profi',
    petSafeRequired: false,
    kidSafeRequired: true,
    notes:
      'Wellness-részleg: magas páratartalom, meleg. Trópusi hangulatot kérnek.',
  },
  {
    code: 'PIXEL',
    name: 'Pixel Stúdió',
    contactName: 'Deák Nóra',
    email: 'nora@pixelstudio.hu',
    city: 'Budapest',
    customerType: 'iroda',
    budget: 140000,
    expertiseLevel: 'haladó',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Sötét szerkesztő-szoba, mesterséges fény. Árnyéktűrő fajokra van szükség.',
  },
  {
    code: 'HORVATH',
    name: 'Horváth Gábor',
    contactName: null,
    email: 'gabor.horvath@gmail.com',
    city: 'Veszprém',
    customerType: 'magánszemély',
    budget: 95000,
    expertiseLevel: 'profi',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Tapasztalt gyűjtő, saját üvegházzal. Ritkaságokat keres, az ár másodlagos.',
  },
  {
    code: 'KISKERT',
    name: 'Kiskert Virágbolt',
    contactName: 'Fodor Adrienn',
    email: 'adrienn@kiskert.hu',
    city: 'Nyíregyháza',
    customerType: 'üzlet',
    budget: 160000,
    expertiseLevel: 'profi',
    petSafeRequired: false,
    kidSafeRequired: false,
    notes:
      'Viszonteladó. Nagyobb tételben vásárol, a raktárkészlet a fő szempont.',
  },
];
