// Szobakertesz — előre generált seed adat (~30 realisztikus növény).
// A mezőnevek a `schema.prisma` `Product` modellje szerint (camelCase). A seedeléshez lásd `seed.ts`.
// Ár HUF-ban. salePrice = null, ha nincs akció. stock = 0 -> nincs raktáron.

export type PlantSeed = {
  name: string
  latinName: string
  category: string // szobanövény | kerti | pozsgás | kaktusz | fűszer | fa-cserje | lógó | virágzó
  location: string // beltéri | kültéri | mindkettő
  price: number
  salePrice: number | null
  stock: number
  light: string // árnyék | alacsony | közepes | erős | direkt nap
  watering: string // ritka | közepes | gyakori | állandóan nedves
  difficulty: string // kezdő | haladó | profi
  currentHeightCm: number
  maxHeightCm: number
  currentPotCm: number
  petSafe: boolean
  kidSafe: boolean
  airPurifying: boolean
  rating: number
  reviewsCount: number
  description: string
}

export const plants: PlantSeed[] = [
  { name: 'Kentia pálma', latinName: 'Howea forsteriana', category: 'szobanövény', location: 'beltéri', price: 18900, salePrice: 15900, stock: 7, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 90, maxHeightCm: 250, currentPotCm: 21, petSafe: true, kidSafe: true, airPurifying: true, rating: 4.7, reviewsCount: 134, description: 'Elegáns, könnyen tartható szobapálma, jól tűri a közepes fényt.' },
  { name: 'Hegedűfügefa', latinName: 'Ficus lyrata', category: 'szobanövény', location: 'beltéri', price: 12900, salePrice: null, stock: 12, light: 'erős', watering: 'közepes', difficulty: 'haladó', currentHeightCm: 70, maxHeightCm: 200, currentPotCm: 19, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.3, reviewsCount: 98, description: 'Látványos, nagy levelű dísznövény, erős, szórt fényt igényel.' },
  { name: 'Vitorlavirág', latinName: 'Spathiphyllum wallisii', category: 'virágzó', location: 'beltéri', price: 4500, salePrice: 3600, stock: 25, light: 'alacsony', watering: 'gyakori', difficulty: 'kezdő', currentHeightCm: 35, maxHeightCm: 60, currentPotCm: 13, petSafe: false, kidSafe: false, airPurifying: true, rating: 4.6, reviewsCount: 210, description: 'Árnyéktűrő, fehéren virágzó klasszikus, kiváló légtisztító.' },
  { name: 'Sárkányfa', latinName: 'Dracaena marginata', category: 'szobanövény', location: 'beltéri', price: 6900, salePrice: null, stock: 18, light: 'alacsony', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 80, maxHeightCm: 180, currentPotCm: 17, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.4, reviewsCount: 76, description: 'Karcsú, keskeny levelű, igénytelen szobanövény kezdőknek.' },
  { name: 'Aranyos pothos', latinName: 'Epipremnum aureum', category: 'lógó', location: 'beltéri', price: 3200, salePrice: null, stock: 40, light: 'alacsony', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 25, maxHeightCm: 150, currentPotCm: 12, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.8, reviewsCount: 312, description: 'Szinte elpusztíthatatlan, gyorsan növő futónövény polcra, szekrény tetejére.' },
  { name: 'Szobafilodendron', latinName: 'Philodendron hederaceum', category: 'lógó', location: 'beltéri', price: 3900, salePrice: null, stock: 22, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 30, maxHeightCm: 120, currentPotCm: 12, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.7, reviewsCount: 145, description: 'Szív alakú leveles, hálás futónövény, alacsony fényt is tűr.' },
  { name: 'Lyukaslevelű filodendron', latinName: 'Monstera deliciosa', category: 'szobanövény', location: 'beltéri', price: 8900, salePrice: 6900, stock: 15, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 55, maxHeightCm: 250, currentPotCm: 17, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.9, reviewsCount: 287, description: 'A népszerű Monstera, hasított leveleivel azonnali dzsungelhangulat.' },
  { name: 'Anyósnyelv', latinName: 'Dracaena trifasciata', category: 'szobanövény', location: 'beltéri', price: 4900, salePrice: null, stock: 30, light: 'alacsony', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 45, maxHeightCm: 90, currentPotCm: 14, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.8, reviewsCount: 198, description: 'A legkönnyebb növény: ritka öntözés, bármilyen fény, erős légtisztító.' },
  { name: 'Zamiokulkász', latinName: 'Zamioculcas zamiifolia', category: 'szobanövény', location: 'beltéri', price: 6500, salePrice: null, stock: 0, light: 'alacsony', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 40, maxHeightCm: 90, currentPotCm: 15, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.7, reviewsCount: 121, description: 'Fényes, viaszos levelű, szárazságtűrő iroda- és lakásnövény.' },
  { name: 'Aloe vera', latinName: 'Aloe vera', category: 'pozsgás', location: 'mindkettő', price: 2500, salePrice: null, stock: 35, light: 'erős', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 25, maxHeightCm: 60, currentPotCm: 12, petSafe: false, kidSafe: true, airPurifying: false, rating: 4.5, reviewsCount: 160, description: 'Hasznos, gyógyító nedvű pozsgás, sok napfénnyel a legszebb.' },
  { name: 'Pénzfa', latinName: 'Crassula ovata', category: 'pozsgás', location: 'beltéri', price: 2900, salePrice: 2200, stock: 28, light: 'erős', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 20, maxHeightCm: 90, currentPotCm: 12, petSafe: false, kidSafe: true, airPurifying: false, rating: 4.6, reviewsCount: 88, description: 'Vastag, kerek levelű pozsgás cserje, a szerencse jelképe.' },
  { name: 'Echeveria', latinName: 'Echeveria elegans', category: 'pozsgás', location: 'beltéri', price: 1500, salePrice: null, stock: 50, light: 'direkt nap', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 8, maxHeightCm: 15, currentPotCm: 8, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.4, reviewsCount: 64, description: 'Rózsa alakú, kékeszöld pozsgás, ablakpárkányra tökéletes.' },
  { name: 'Aranylabda kaktusz', latinName: 'Echinocactus grusonii', category: 'kaktusz', location: 'beltéri', price: 3500, salePrice: null, stock: 16, light: 'direkt nap', watering: 'ritka', difficulty: 'kezdő', currentHeightCm: 15, maxHeightCm: 80, currentPotCm: 13, petSafe: true, kidSafe: false, airPurifying: false, rating: 4.5, reviewsCount: 42, description: 'Gömb alakú, tüskés gyűjtői kaktusz, nagyon kevés vízzel.' },
  { name: 'Karácsonyi kaktusz', latinName: 'Schlumbergera truncata', category: 'kaktusz', location: 'beltéri', price: 2800, salePrice: null, stock: 20, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 20, maxHeightCm: 40, currentPotCm: 12, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.6, reviewsCount: 73, description: 'Télen látványosan virágzó lógó kaktusz, állatbarát.' },
  { name: 'Bazsalikom', latinName: 'Ocimum basilicum', category: 'fűszer', location: 'mindkettő', price: 990, salePrice: null, stock: 60, light: 'erős', watering: 'gyakori', difficulty: 'kezdő', currentHeightCm: 18, maxHeightCm: 45, currentPotCm: 11, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.2, reviewsCount: 51, description: 'Friss konyhai fűszer, napos ablakban folyamatosan szedhető.' },
  { name: 'Rozmaring', latinName: 'Salvia rosmarinus', category: 'fűszer', location: 'mindkettő', price: 1490, salePrice: null, stock: 33, light: 'direkt nap', watering: 'ritka', difficulty: 'haladó', currentHeightCm: 25, maxHeightCm: 120, currentPotCm: 13, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.3, reviewsCount: 47, description: 'Illatos, örökzöld konyhai cserje, sok napot és kevés vizet kér.' },
  { name: 'Levendula', latinName: 'Lavandula angustifolia', category: 'virágzó', location: 'kültéri', price: 1990, salePrice: 1590, stock: 45, light: 'direkt nap', watering: 'ritka', difficulty: 'haladó', currentHeightCm: 25, maxHeightCm: 70, currentPotCm: 14, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.7, reviewsCount: 156, description: 'Illatos, lila virágú kerti félcserje, méhbarát és szárazságtűrő.' },
  { name: 'Borostyán', latinName: 'Hedera helix', category: 'lógó', location: 'mindkettő', price: 2200, salePrice: null, stock: 38, light: 'alacsony', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 20, maxHeightCm: 200, currentPotCm: 12, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.4, reviewsCount: 69, description: 'Örökzöld kúszónövény bel- és kültérre, gyorsan benövi a felületet.' },
  { name: 'Boston páfrány', latinName: 'Nephrolepis exaltata', category: 'szobanövény', location: 'beltéri', price: 3400, salePrice: null, stock: 19, light: 'közepes', watering: 'gyakori', difficulty: 'haladó', currentHeightCm: 35, maxHeightCm: 70, currentPotCm: 15, petSafe: true, kidSafe: true, airPurifying: true, rating: 4.2, reviewsCount: 58, description: 'Dús, lecsüngő páfrány, párás környezetet és rendszeres vizet kér.' },
  { name: 'Calathea', latinName: 'Calathea orbifolia', category: 'szobanövény', location: 'beltéri', price: 5900, salePrice: null, stock: 11, light: 'közepes', watering: 'gyakori', difficulty: 'profi', currentHeightCm: 30, maxHeightCm: 90, currentPotCm: 15, petSafe: true, kidSafe: true, airPurifying: true, rating: 4.1, reviewsCount: 64, description: 'Mintás, ezüstcsíkos levelek; igényes a páratartalomra és a vízminőségre.' },
  { name: 'Lepkeorchidea', latinName: 'Phalaenopsis', category: 'virágzó', location: 'beltéri', price: 4200, salePrice: 3200, stock: 27, light: 'közepes', watering: 'ritka', difficulty: 'haladó', currentHeightCm: 45, maxHeightCm: 70, currentPotCm: 12, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.5, reviewsCount: 188, description: 'Hetekig nyíló, elegáns szobaorchidea, állatbarát ajándéknövény.' },
  { name: 'Királybegónia', latinName: 'Begonia rex', category: 'virágzó', location: 'beltéri', price: 3100, salePrice: null, stock: 14, light: 'közepes', watering: 'közepes', difficulty: 'haladó', currentHeightCm: 22, maxHeightCm: 40, currentPotCm: 13, petSafe: false, kidSafe: true, airPurifying: false, rating: 4.0, reviewsCount: 37, description: 'Színes, mintás levélzetéért tartott dísznövény, szórt fényben a legszebb.' },
  { name: 'Muskátli', latinName: 'Pelargonium', category: 'virágzó', location: 'kültéri', price: 1290, salePrice: null, stock: 70, light: 'direkt nap', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 20, maxHeightCm: 50, currentPotCm: 12, petSafe: false, kidSafe: true, airPurifying: false, rating: 4.3, reviewsCount: 92, description: 'Klasszikus balkonvirág, egész nyáron folyamatosan virágzik.' },
  { name: 'Japán juhar', latinName: 'Acer palmatum', category: 'fa-cserje', location: 'kültéri', price: 12500, salePrice: null, stock: 6, light: 'közepes', watering: 'közepes', difficulty: 'profi', currentHeightCm: 60, maxHeightCm: 400, currentPotCm: 23, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.8, reviewsCount: 41, description: 'Finom lombú, ősszel tűzpirosan színeződő díszfa, félárnyékot kedvel.' },
  { name: 'Olajfa', latinName: 'Olea europaea', category: 'fa-cserje', location: 'mindkettő', price: 15900, salePrice: 12900, stock: 9, light: 'direkt nap', watering: 'ritka', difficulty: 'haladó', currentHeightCm: 80, maxHeightCm: 300, currentPotCm: 24, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.6, reviewsCount: 53, description: 'Mediterrán, ezüstös lombú fa terasra; sok nap, kevés víz.' },
  { name: 'Citromfa', latinName: 'Citrus limon', category: 'fa-cserje', location: 'mindkettő', price: 9900, salePrice: null, stock: 13, light: 'direkt nap', watering: 'közepes', difficulty: 'haladó', currentHeightCm: 50, maxHeightCm: 200, currentPotCm: 21, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.4, reviewsCount: 67, description: 'Illatos virágú, termő dézsás citrusfa napos, védett helyre.' },
  { name: 'Puszpáng', latinName: 'Buxus sempervirens', category: 'kerti', location: 'kültéri', price: 3800, salePrice: null, stock: 24, light: 'közepes', watering: 'közepes', difficulty: 'haladó', currentHeightCm: 30, maxHeightCm: 200, currentPotCm: 17, petSafe: false, kidSafe: true, airPurifying: false, rating: 4.2, reviewsCount: 39, description: 'Sűrű, formázható örökzöld sövény- és szegélynövény.' },
  { name: 'Gumifikusz', latinName: 'Ficus elastica', category: 'szobanövény', location: 'beltéri', price: 5500, salePrice: null, stock: 21, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 60, maxHeightCm: 250, currentPotCm: 17, petSafe: false, kidSafe: true, airPurifying: true, rating: 4.5, reviewsCount: 104, description: 'Fényes, bőrszerű levelű, mutatós és könnyen tartható szobafa.' },
  { name: 'Kínai pénzfa', latinName: 'Pilea peperomioides', category: 'szobanövény', location: 'beltéri', price: 2900, salePrice: null, stock: 32, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 18, maxHeightCm: 30, currentPotCm: 11, petSafe: true, kidSafe: true, airPurifying: false, rating: 4.7, reviewsCount: 129, description: 'Kerek, érme alakú levelek; könnyen szaporítható, állatbarát kedvenc.' },
  { name: 'Szobafenyő', latinName: 'Araucaria heterophylla', category: 'szobanövény', location: 'beltéri', price: 7200, salePrice: null, stock: 8, light: 'erős', watering: 'közepes', difficulty: 'kezdő', currentHeightCm: 50, maxHeightCm: 200, currentPotCm: 17, petSafe: true, kidSafe: true, airPurifying: true, rating: 4.3, reviewsCount: 45, description: 'Örökzöld, fenyőszerű szobanövény, télen élő karácsonyfa-alternatíva.' },
]
